name: Java Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: travisj/build-number-action@v1
      id: my-project-build-number
    - name: Echo Build Number
      run: echo $BUILD_NUMBER
      env:
        BUILD_NUMBER: ${{ steps.my-project-build-number.outputs.build-number }}
    - name: Checkout
      uses: actions/checkout@v2.4.2
      with: 
        repository: "cataclysm-interactive/PokemonBattler"
    - name: Setup Java JDK
      uses: actions/setup-java@v3.3.0
      with: 
        java-version: 17
        distribution: temurin
    - name: Compile Code
      run: |
        cd battler
        javac mainGame.java Pokemon.java Trainer.java Move.java
        ls
    - name: Package into JAR
      run: |
        jar cfe pkmn.jar mainGame battler
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}        
      with:
        tag_name: ${{ steps.my-project-build-number.outputs.build-number }}
        release_name: ${{ github.event.head_commit.message }}
        draft: true
        prerelease: false
    - name: Publish Artifact
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: pkmn.jar
        asset_name: pkmn.jar
        asset_content_type: application/jar
        
      
      

